"""updated db

Revision ID: 0094bfd111aa
Revises: 0c085fbc1177
Create Date: 2023-07-19 02:33:46.390824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0094bfd111aa'
down_revision = '0c085fbc1177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_cuisine_genres',
    sa.Column('restaurant_id', sa.String(length=32), nullable=True),
    sa.Column('cuisine_genre', sa.Enum('THAI', 'VIETNAMESE', 'SOUTHEAST_ASIAN', 'KOREAN', 'CHINESE', 'JAPANESE', 'INDIAN', 'ITALIAN', 'FRENCH', 'AMERICAN', 'MEXICAN', 'SOUTH_AMERICAN', 'MIDDLE_EASTERN', 'MEDITERRANEAN', name='cuisinegenre'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.UniqueConstraint('restaurant_id', 'cuisine_genre')
    )
    op.create_table('restaurant_dietary_preferences',
    sa.Column('restaurant_id', sa.String(length=32), nullable=True),
    sa.Column('dietary_preference', sa.Enum('VEGAN', 'VEGETARIAN', 'PESCETARIAN', 'GLUTEN_FREE', 'DAIRY_FREE', 'NUT_FREE', 'HALAL', name='dietarypreference'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.UniqueConstraint('restaurant_id', 'dietary_preference')
    )
    op.create_table('user_cuisine_genres',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('cuisine_genre', sa.Enum('THAI', 'VIETNAMESE', 'SOUTHEAST_ASIAN', 'KOREAN', 'CHINESE', 'JAPANESE', 'INDIAN', 'ITALIAN', 'FRENCH', 'AMERICAN', 'MEXICAN', 'SOUTH_AMERICAN', 'MIDDLE_EASTERN', 'MEDITERRANEAN', name='cuisinegenre'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'cuisine_genre')
    )
    op.create_table('user_spending_budgets',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('spending_budget', sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='spendingbudget'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'spending_budget')
    )
    op.add_column('restaurant', sa.Column('spending_budget', sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='spendingbudget'), nullable=True))
    op.alter_column('user_dietary_preferences', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.create_unique_constraint(None, 'user_dietary_preferences', ['user_id', 'dietary_preference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_dietary_preferences', type_='unique')
    op.alter_column('user_dietary_preferences', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('restaurant', 'spending_budget')
    op.drop_table('user_spending_budgets')
    op.drop_table('user_cuisine_genres')
    op.drop_table('restaurant_dietary_preferences')
    op.drop_table('restaurant_cuisine_genres')
    # ### end Alembic commands ###
