"""update UUID

Revision ID: 03f1c8b9421c
Revises: f09a7813f5bf
Create Date: 2023-07-22 14:05:24.653027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f1c8b9421c'
down_revision = 'f09a7813f5bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
