"""update int length

Revision ID: 06565af0f8a3
Revises: 03f1c8b9421c
Create Date: 2023-07-22 14:15:18.745422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06565af0f8a3'
down_revision = '03f1c8b9421c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
