"""updated db

Revision ID: 0d3aa55fbcfc
Revises: 0094bfd111aa
Create Date: 2023-07-19 02:35:12.016485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d3aa55fbcfc'
down_revision = '0094bfd111aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_dietary_preferences', 'dietary_preference',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'user_dietary_preferences', ['user_id', 'dietary_preference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_dietary_preferences', type_='unique')
    op.alter_column('user_dietary_preferences', 'dietary_preference',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
