"""update int length

Revision ID: 122007654f24
Revises: 453404ecc6ee
Create Date: 2023-07-22 14:36:19.655719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '122007654f24'
down_revision = '453404ecc6ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite_restaurants', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('favorite_restaurants', 'restaurant_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('restaurant', 'id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('restaurant_cuisine_genres', 'restaurant_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('restaurant_dietary_preferences', 'restaurant_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('user_cuisine_genres', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('user_dietary_preferences', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('user_dietary_preferences', 'dietary_preference',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Enum('VEGAN', 'VEGETARIAN', 'PESCETARIAN', 'GLUTEN_FREE', 'DAIRY_FREE', 'NUT_FREE', 'HALAL', name='dietarypreference'),
               existing_nullable=False)
    op.alter_column('user_restaurant_rating', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('user_restaurant_rating', 'restaurant_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('user_spending_budgets', 'user_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users_following', 'follower_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users_following', 'followed_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_following', 'followed_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users_following', 'follower_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('user_spending_budgets', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('user_restaurant_rating', 'restaurant_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('user_restaurant_rating', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('user_dietary_preferences', 'dietary_preference',
               existing_type=sa.Enum('VEGAN', 'VEGETARIAN', 'PESCETARIAN', 'GLUTEN_FREE', 'DAIRY_FREE', 'NUT_FREE', 'HALAL', name='dietarypreference'),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('user_dietary_preferences', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_cuisine_genres', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('restaurant_dietary_preferences', 'restaurant_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('restaurant_cuisine_genres', 'restaurant_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('restaurant', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('favorite_restaurants', 'restaurant_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('favorite_restaurants', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
