"""update int length

Revision ID: 19a01e9f9437
Revises: 774f16641771
Create Date: 2023-07-22 14:20:50.671162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a01e9f9437'
down_revision = '774f16641771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
