"""update int length

Revision ID: 774f16641771
Revises: 06565af0f8a3
Create Date: 2023-07-22 14:19:52.020407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774f16641771'
down_revision = '06565af0f8a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
