"""Initial migration

Revision ID: c3a8337cfbf5
Revises: eb75fbefbc9b
Create Date: 2023-07-19 02:02:34.567524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a8337cfbf5'
down_revision = 'eb75fbefbc9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_restaurants',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('restaurant_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_dietary_preferences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('dietary_preference', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_restaurant_rating',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('restaurant_id', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('users_following',
    sa.Column('follower_id', sa.String(length=32), nullable=True),
    sa.Column('followed_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_following')
    op.drop_table('user_restaurant_rating')
    op.drop_table('user_dietary_preferences')
    op.drop_table('favorite_restaurants')
    # ### end Alembic commands ###
