"""updated db

Revision ID: d96670c3dd92
Revises: 0d3aa55fbcfc
Create Date: 2023-07-19 04:13:53.885185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96670c3dd92'
down_revision = '0d3aa55fbcfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('restaurant_id', sa.String(length=32), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id')
    )
    op.add_column('restaurant', sa.Column('phone_number', sa.String(length=64), nullable=True))
    op.add_column('restaurant', sa.Column('operating_hours', sa.String(length=64), nullable=True))
    op.add_column('restaurant', sa.Column('by_reservation_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'by_reservation_only')
    op.drop_column('restaurant', 'operating_hours')
    op.drop_column('restaurant', 'phone_number')
    op.drop_table('review')
    # ### end Alembic commands ###
