"""update int length

Revision ID: dbcbd47c3828
Revises: 19a01e9f9437
Create Date: 2023-07-22 14:22:29.432514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcbd47c3828'
down_revision = '19a01e9f9437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
