"""testAgain

Revision ID: f09a7813f5bf
Revises: 0b1e62f00c48
Create Date: 2023-07-21 17:17:20.123466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09a7813f5bf'
down_revision = '0b1e62f00c48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
